from django.db import models

# Create your models here.
class Profile(models.Model):
    name=models.CharField(max_length=100)
    about=models.TextField(max_length=1000)
    addline1=models.CharField(max_length=100)
    addline2=models.CharField(max_length=100)
    phone=models.CharField(max_length=10)
    email=models.CharField(max_length=100)
    com1=models.CharField(max_length=100)
    loc1=models.CharField(max_length=100)
    job1=models.CharField(max_length=100)
    des1=models.TextField(max_length=1000)
    com2=models.CharField(max_length=100)
    loc2=models.CharField(max_length=100)
    job2=models.CharField(max_length=100)
    des2=models.TextField(max_length=1000)
    college=models.CharField(max_length=100)
    sloc1=models.CharField(max_length=100)
    degree=models.CharField(max_length=100)
    branch=models.CharField(max_length=100)
    sdes1=models.TextField(max_length=1000)
    school1=models.CharField(max_length=100)
    sloc2=models.CharField(max_length=100)
    sdes2=models.TextField(max_length=1000)
    school2=models.CharField(max_length=100)
    sloc3=models.CharField(max_length=100)
    sdes3=models.TextField(max_length=1000)
    skill1=models.CharField(max_length=100)
    skill2=models.CharField(max_length=100)
    skill3=models.CharField(max_length=100)
    skill4=models.CharField(max_length=100)
    project1=models.CharField(max_length=100)
    project2=models.CharField(max_length=100)
    project3=models.CharField(max_length=100)
    project4=models.CharField(max_length=100)